[Pushover]
    Token=""
    UserKey=""
#   to add more pushover notifiers, uncomment and use the example below
#   Additional = [
#       { Token = "token P2", UserKey = "userKey P2"},
#       { Token = "token P3", UserKey = "userKey P3"},
#   ]

[Smtp]
    Email="from@email.com"
    Password=""

[Telegram]
    Token=""
    ChatID=""
#   to add more telegram notifiers, uncomment and use the example below
#   Additional = [
#       { Token = "token T2", ChatID = "chatID T2"},
#       { Token = "token T3", ChatID = "chatID T3"},
#   ]

[Slack]
    Secret=""
#   to add more telegram notifiers, uncomment and use the example below
#   Additional = [
#       { Secret = "s1"},
#       { Secret = "s2"},
#   ]
